CREATE OR REPLACE FUNCTION Date2EnrollYear(dDate IN DATE) 
RETURN NUMBER
IS
	eYear NUMBER; 
BEGIN 
SELECT TO_NUMBER(TO_CHAR(dDate, 'YYYY')) 
	INTO eYear
	FROM DUAL;

	RETURN eYear;
END; 
/
